"""empty message

Revision ID: 773abaeab45d
Revises: ef00c0792461
Create Date: 2024-06-09 16:13:12.342913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773abaeab45d'
down_revision = 'ef00c0792461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('about_me', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('about_me')
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
